version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: 'ci: ğŸ‘· '
  - package-ecosystem: npm
    directory: /
    commit-message:
      prefix: 'build: â¬†ï¸ '
